language: generic
##travissss
before_deploy:
  - git config --local user.name "srikar45"
  - git config --local user.email "ksreddy4599@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - tar -zcf ${TRAVIS_TAG}.tar.gz *

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ${TRAVIS_TAG}.tar.gz
  skip_cleanup: true

after_deploy:
  - curl -L https://github.com/hapi-server/server-nodejs/releases/download/$TRAVIS_TAG/$TRAVIS_TAG.tgz | tar zxf -
  - cd hapi-server-$TRAVIS_TAG
  - ./hapi-server --test
