language: generic
before_deploy:
  - npm run package
  - npm run release
  - npm run update

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true

after_deploy:
  - npm run package
  - npm run release
  - npm run update
