language: generic
before_deploy:
  - npm i release-it --save
  - npm run package
  - npm run release
  - GITHUB_TOKEN=$GITHUB_OAUTH_TOKEN && release-it $(VERSION) --preRelease=beta --no-git.requireCleanWorkingDir --no-npm.publish
  - npm run update

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true

after_deploy:
  - npm run update
  - npm run package
  - npm run test-packages
