language: generic
before_deploy:
  - "echo 'ready???'"
  #ß#- git config --local user.name "srikar45"##
  #- git config --local user.email "ksreddy4599@gmail.com"
  #- tar -zcf ${TRAVIS_TAG}.tar.gz *
  - npm install release-it
  - npm run package
  - npm run release
  - npm run update

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true

after_deploy:
  - npm run package
  - npm run release
  - npm run update
