language: generic
########

before_deploy:
  - git config --local user.name "srikar45"
  - git config --local user.email "ksreddy4599@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true

after_deploy:
  - echo $TRAVIS_TAG
