language: generic
##travissss
before_deploy:
  - git config --local user.name "srikar45"
  - git config --local user.email "ksreddy4599@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - tar -zcf ${TRAVIS_TAG}.tar.gz *

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ${TRAVIS_TAG}.tar.gz
  skip_cleanup: true

after_deploy:
  - mkdir dest
  - cd dest
  - curl -L https://github.com/srikar45/serverzz/releases/download/20210701184415-1ba858f/20210701184415-1ba858f.tar.gz | tar zxf -
  - ./hapi-server --test
