language: generic
##travissss
before_deploy:
  - "echo 'ready?'"
  - git config --local user.name "srikar45"
  - git config --local user.email "ksreddy4599@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - tar -zcf ${TRAVIS_TAG}.tar.gz *

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ${TRAVIS_TAG}.tar.gz
  skip_cleanup: true

after_deploy:
  - ./tester_lol.sh
